<?xml version="1.0" encoding="utf-8"?><Database Name="QL_HOMESTAY" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=QL_HOMESTAY;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_HOMESTAYConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CTDV" Member="CTDVs">
    <Type Name="CTDV">
      <Column Name="MADV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MACTDV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DICHVU_CTDV" Member="DICHVU" ThisKey="MADV" OtherKey="MADV" Type="DICHVU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="MATK" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="QUYEN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="TAIKHOAN_KHACHHANG" Member="KHACHHANGs" ThisKey="MATK" OtherKey="MATK" Type="KHACHHANG" />
      <Association Name="TAIKHOAN_NHANVIEN" Member="NHANVIENs" ThisKey="MATK" OtherKey="MATK" Type="NHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.CTHD" Member="CTHDs">
    <Type Name="CTHD">
      <Column Name="MACTHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MADV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GIAMGIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TONGTIENTHANHTOAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DICHVU_CTHD" Member="DICHVU" ThisKey="MADV" OtherKey="MADV" Type="DICHVU" IsForeignKey="true" />
      <Association Name="HOADON_CTHD" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHOPDONG" Member="CTHOPDONGs">
    <Type Name="CTHOPDONG">
      <Column Name="MAHOPDONG" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MACTHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="THOIHAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIENCOC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="HOPDONG_CTHOPDONG" Member="HOPDONG" ThisKey="MAHOPDONG" OtherKey="MAHOPDONG" Type="HOPDONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTKHUYENMAI" Member="CTKHUYENMAIs">
    <Type Name="CTKHUYENMAI">
      <Column Name="MACTKM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKHUYENMAI" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NGAYBD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGAYKT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIAKM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="KHUYENMAI_CTKHUYENMAI" Member="KHUYENMAI" ThisKey="MAKHUYENMAI" OtherKey="MAKHUYENMAI" Type="KHUYENMAI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANHGIA" Member="DANHGIAs">
    <Type Name="DANHGIA">
      <Column Name="MADG" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NOIDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="KHACHHANG_DANHGIA" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DICHVU" Member="DICHVUs">
    <Type Name="DICHVU">
      <Column Name="MADV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDV" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MAPHONG" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="DICHVU_CTDV" Member="CTDVs" ThisKey="MADV" OtherKey="MADV" Type="CTDV" />
      <Association Name="DICHVU_CTHD" Member="CTHDs" ThisKey="MADV" OtherKey="MADV" Type="CTHD" />
      <Association Name="PHONG_DICHVU" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MAHOPDONG" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MAPHONG" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="HOADON_CTHD" Member="CTHDs" ThisKey="MAHD" OtherKey="MAHD" Type="CTHD" />
      <Association Name="HOPDONG_HOADON" Member="HOPDONG" ThisKey="MAHOPDONG" OtherKey="MAHOPDONG" Type="HOPDONG" IsForeignKey="true" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="PHONG_HOADON" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOPDONG" Member="HOPDONGs">
    <Type Name="HOPDONG">
      <Column Name="MAHOPDONG" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHONG" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MAKHACH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="THOIGIANTAO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="HOPDONG_CTHOPDONG" Member="CTHOPDONGs" ThisKey="MAHOPDONG" OtherKey="MAHOPDONG" Type="CTHOPDONG" />
      <Association Name="HOPDONG_HOADON" Member="HOADONs" ThisKey="MAHOPDONG" OtherKey="MAHOPDONG" Type="HOADON" />
      <Association Name="KHACHHANG_HOPDONG" Member="KHACHHANG" ThisKey="MAKHACH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="PHONG_HOPDONG" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="QUEQUAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MATK" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="KHACHHANG_DANHGIA" Member="DANHGIAs" ThisKey="MAKH" OtherKey="MAKH" Type="DANHGIA" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="MAKH" OtherKey="MAKH" Type="HOADON" />
      <Association Name="KHACHHANG_HOPDONG" Member="HOPDONGs" ThisKey="MAKH" OtherKey="MAKHACH" Type="HOPDONG" />
      <Association Name="TAIKHOAN_KHACHHANG" Member="TAIKHOAN" ThisKey="MATK" OtherKey="MATK" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHU" Member="KHUs">
    <Type Name="KHU">
      <Column Name="MAKHU" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKHU" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="KHU_PHONG" Member="PHONGs" ThisKey="MAKHU" OtherKey="MAKHU" Type="PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="MAKHUYENMAI" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKHUYENMAI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MAPHONG" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="KHUYENMAI_CTKHUYENMAI" Member="CTKHUYENMAIs" ThisKey="MAKHUYENMAI" OtherKey="MAKHUYENMAI" Type="CTKHUYENMAI" />
      <Association Name="PHONG_KHUYENMAI" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIPHONG" Member="LOAIPHONGs">
    <Type Name="LOAIPHONG">
      <Column Name="MALOAI" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GIAPH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="LOAIPHONG_PHONG" Member="PHONGs" ThisKey="MALOAI" OtherKey="MALOAIPHONG" Type="PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="QUEQUAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CHUCVU" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MATK" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="TAIKHOAN_NHANVIEN" Member="TAIKHOAN" ThisKey="MATK" OtherKey="MATK" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG" Member="PHONGs">
    <Type Name="PHONG">
      <Column Name="MAPHONG" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAIPHONG" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MAKHU" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TENPHONG" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SOLUONGNGUOIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="PHONG_DICHVU" Member="DICHVUs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="DICHVU" />
      <Association Name="PHONG_HOADON" Member="HOADONs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="HOADON" />
      <Association Name="PHONG_HOPDONG" Member="HOPDONGs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="HOPDONG" />
      <Association Name="PHONG_KHUYENMAI" Member="KHUYENMAIs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="KHUYENMAI" />
      <Association Name="KHU_PHONG" Member="KHU" ThisKey="MAKHU" OtherKey="MAKHU" Type="KHU" IsForeignKey="true" />
      <Association Name="LOAIPHONG_PHONG" Member="LOAIPHONG" ThisKey="MALOAIPHONG" OtherKey="MALOAI" Type="LOAIPHONG" IsForeignKey="true" />
    </Type>
  </Table>
</Database>